# Generated by Django 2.0.2 on 2018-02-28 21:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageS1',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=67)),
                ('ingestiondate', models.DateTimeField()),
                ('satellite', models.CharField(max_length=3)),
                ('mode', models.CharField(max_length=2)),
                ('orbitdirection', models.CharField(max_length=10)),
                ('polarisationmode', models.CharField(max_length=5)),
                ('producttype', models.CharField(max_length=3)),
                ('relativeorbitnumber', models.IntegerField()),
                ('size', models.IntegerField()),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ImageS2',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('ingestiondate', models.DateTimeField()),
                ('satellite', models.CharField(max_length=3)),
                ('mode', models.CharField(max_length=8)),
                ('orbitdirection', models.CharField(max_length=10)),
                ('cloudcover', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producttype', models.CharField(max_length=7)),
                ('relativeorbitnumber', models.IntegerField()),
                ('size', models.IntegerField()),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
